"""praxa_core - shared, surface-agnostic core for all Praxa agents."""

from ._utils import logger, sanitize_sql_like_pattern, infer_bucket_style
from .context import (
    ToolContext,
    EMAIL_CACHE_TTL,
    format_event_time,
    pick_primary_calendar,
    auto_update_tz,
    resolve_calendar_target_day,
    calendar_no_events_for_day_message,
    calendar_no_events_upcoming_message,
)
from .actions import (
    ACTION_MANIFEST,
    ActionSpec,
    AUTO,
    CONFIRM,
    STATUS_QUEUED,
    STATUS_PENDING_CONFIRMATION,
    STATUS_CONFIRMED,
    STATUS_RUNNING,
    STATUS_DONE,
    STATUS_FAILED,
    STATUS_CANCELLED,
    get_action_spec,
    classify_action,
    requires_confirmation,
    queue_action,
)
from .memory import embed_text, get_relevant_context
from . import email_filter
from .tools import tasks, buckets, calendar, email, integrations

__all__ = [
    "logger",
    "sanitize_sql_like_pattern",
    "infer_bucket_style",
    "ToolContext",
    "EMAIL_CACHE_TTL",
    "format_event_time",
    "pick_primary_calendar",
    "auto_update_tz",
    "resolve_calendar_target_day",
    "calendar_no_events_for_day_message",
    "calendar_no_events_upcoming_message",
    "ACTION_MANIFEST",
    "ActionSpec",
    "AUTO",
    "CONFIRM",
    "STATUS_QUEUED",
    "STATUS_PENDING_CONFIRMATION",
    "STATUS_CONFIRMED",
    "STATUS_RUNNING",
    "STATUS_DONE",
    "STATUS_FAILED",
    "STATUS_CANCELLED",
    "get_action_spec",
    "classify_action",
    "requires_confirmation",
    "queue_action",
    "embed_text",
    "get_relevant_context",
    "email_filter",
    "tasks",
    "buckets",
    "calendar",
    "email",
    "integrations",
]
